name: CI

on: [push]

jobs:
  deploy:
    name: Publish release
    runs-on: ubuntu-20.04
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: Do release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
